# Generated by Django 5.2.10 on 2026-01-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='奖金标题')),
                ('team_name', models.CharField(max_length=50, verbose_name='目标班组')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('completed', '已分配/已上报')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配件名称')),
                ('category', models.CharField(choices=[('part', '配件'), ('material', '辅材')], default='part', max_length=20)),
                ('spec', models.CharField(blank=True, default='', max_length=50, verbose_name='规格型号')),
                ('stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('unit', models.CharField(default='个', max_length=10, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('role', models.CharField(choices=[('driver', '司机'), ('repairman', '修理工'), ('team_leader', '班长'), ('dispatcher', '调度员'), ('leader', '车队领导'), ('admin', '超级管理员')], default='driver', max_length=20, verbose_name='角色')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属班组')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('work_status', models.CharField(default='off_duty', max_length=20, verbose_name='工作状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet.bonusbatch')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='领款人')),
            ],
        ),
        migrations.AddField(
            model_name='bonusbatch',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_batches', to='fleet.employee', verbose_name='接收班长'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=50, verbose_name='故障类型')),
                ('content', models.TextField(default='', verbose_name='维修内容')),
                ('status', models.CharField(choices=[('pending', '待接单'), ('fixing', '维修中'), ('completed', '已完工')], default='pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('is_routine_maintenance', models.BooleanField(default=False, verbose_name='是否例行保养')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_repairs', to='fleet.employee')),
                ('repairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_repairs', to='fleet.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='fleet.maintenancerecord')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('remark', models.CharField(blank=True, default='', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.employee')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True, verbose_name='自编号')),
                ('plate_number', models.CharField(max_length=20, verbose_name='车牌号')),
                ('brand_model', models.CharField(blank=True, default='', max_length=50, verbose_name='品牌型号')),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=20, verbose_name='车辆种类')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('working', '作业中'), ('repairing', '维修中')], default='idle', max_length=20)),
                ('current_mileage', models.IntegerField(default=0, verbose_name='当前里程')),
                ('maintenance_strategy', models.CharField(default='mixed', max_length=20, verbose_name='保养策略')),
                ('interval_km', models.IntegerField(default=5000, verbose_name='保养间隔里程')),
                ('interval_days', models.IntegerField(default=90, verbose_name='保养间隔天数')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保养日期')),
                ('last_maintenance_mileage', models.IntegerField(default=0, verbose_name='上次保养里程')),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_mileage', models.IntegerField(default=0)),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='保险到期')),
                ('inspection_expiry', models.DateField(blank=True, null=True, verbose_name='年检到期')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='fleet.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('fuel', '加油'), ('urea', '尿素'), ('charge', '充电')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金额')),
                ('mileage', models.IntegerField(verbose_name='当前里程')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('remark', models.TextField(blank=True, default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target_team', models.CharField(max_length=50, verbose_name='目标班组')),
                ('detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', '待分配'), ('assigned', '进行中'), ('completed', '已完成')], default='new', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_drivers', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='fleet.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='fleet.employee')),
            ],
        ),
    ]
