# Generated by Django 5.2.10 on 2026-01-19 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusbatch',
            options={'verbose_name': '奖金包', 'verbose_name_plural': '奖金包'},
        ),
        migrations.AlterModelOptions(
            name='bonusdetail',
            options={'verbose_name': '奖金明细', 'verbose_name_plural': '奖金明细'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工档案', 'verbose_name_plural': '员工档案'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': '库存配件', 'verbose_name_plural': '库存配件'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'verbose_name': '维修保养工单', 'verbose_name_plural': '维修保养工单'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name': '运营/能耗记录', 'verbose_name_plural': '运营/能耗记录'},
        ),
        migrations.AlterModelOptions(
            name='partusage',
            options={'verbose_name': '配件使用记录', 'verbose_name_plural': '配件使用记录'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'verbose_name': '库存变动日志', 'verbose_name_plural': '库存变动日志'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': '车辆档案', 'verbose_name_plural': '车辆档案'},
        ),
        migrations.AlterModelOptions(
            name='worktask',
            options={'verbose_name': '工作任务', 'verbose_name_plural': '工作任务'},
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发放时间'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='status',
            field=models.CharField(choices=[('pending', '待分配'), ('completed', '已分配/已上报')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('driver', '司机'), ('repairman', '修理'), ('team_leader', '班长'), ('dispatcher', '调度员'), ('leader', '车队领导'), ('admin', '超级管理员')], default='driver', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('part', '配件'), ('material', '辅材')], default='part', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总费用'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='报修时间'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_repairs', to='fleet.employee', verbose_name='报修人'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完工时间'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='repairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_repairs', to='fleet.employee', verbose_name='维修技师'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('pending', '待接单'), ('fixing', '维修中'), ('completed', '已完工')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='维修车辆'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='填报时间'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='驾驶员'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='小票照片'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='record_type',
            field=models.CharField(choices=[('fuel', '加油'), ('urea', '尿素'), ('charge', '充电')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='车辆'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem', verbose_name='配件'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='action',
            field=models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.employee', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem', verbose_name='配件'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='fleet.employee', verbose_name='当前驾驶员'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次保养日期'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='next_maintenance_mileage',
            field=models.IntegerField(default=0, verbose_name='下次保养里程'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('working', '作业中'), ('repairing', '维修中')], default='idle', max_length=20, verbose_name='车辆状态'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assigned_drivers',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='fleet.employee', verbose_name='执行司机'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='fleet.employee', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='detail',
            field=models.TextField(blank=True, default='', verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('new', '待分配'), ('assigned', '进行中'), ('completed', '已完成')], default='new', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='title',
            field=models.CharField(max_length=100, verbose_name='任务标题'),
        ),
    ]
