# Generated by Django 5.2.10 on 2026-01-19 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_bonusbatch_options_alter_bonusdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusbatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bonusdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partusage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worktask',
            options={},
        ),
        migrations.RemoveField(
            model_name='bonusbatch',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='is_routine_maintenance',
        ),
        migrations.RemoveField(
            model_name='operationrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='operationrecord',
            name='location',
        ),
        migrations.RemoveField(
            model_name='operationrecord',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='partusage',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='stocklog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='stocklog',
            name='part',
        ),
        migrations.RemoveField(
            model_name='stocklog',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stocklog',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='inspection_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='interval_days',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='interval_km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='maintenance_strategy',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_maintenance_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='finish_at',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='target_team',
        ),
        migrations.AddField(
            model_name='bonusbatch',
            name='month',
            field=models.CharField(default='2026-01', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonusbatch',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='repairs/'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklog',
            name='change_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklog',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklog',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktask',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.bonusbatch'),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('driver', '司机'), ('repairman', '修理工'), ('team_leader', '班长'), ('dispatcher', '调度员'), ('admin', '管理员')], default='driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('on_duty', '在岗'), ('off_duty', '休息')], default='off_duty', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('spare', '备品'), ('material', '辅材')], default='spare', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_repairs', to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='fault_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='repairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repairs', to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('pending', '待维修'), ('repairing', '维修中'), ('completed', '已完成')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='record_type',
            field=models.CharField(choices=[('fuel', '加油'), ('charge', '充电')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.maintenancerecord'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_vehicle', to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('working', '作业中'), ('repairing', '维修中')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assigned_drivers',
            field=models.ManyToManyField(related_name='tasks', to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='fleet.employee'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
