# Generated by Django 5.2.10 on 2026-01-19 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_bonusbatch_options_alter_bonusdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusbatch',
            options={'verbose_name': '奖金批次', 'verbose_name_plural': '奖金批次'},
        ),
        migrations.AlterModelOptions(
            name='bonusdetail',
            options={'verbose_name': '奖金明细', 'verbose_name_plural': '奖金明细'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': '库存物品', 'verbose_name_plural': '库存物品'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'verbose_name': '维修记录', 'verbose_name_plural': '维修记录'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name': '运营记录', 'verbose_name_plural': '运营记录'},
        ),
        migrations.AlterModelOptions(
            name='partusage',
            options={'verbose_name': '配件使用记录', 'verbose_name_plural': '配件使用记录'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'verbose_name': '库存变动日志', 'verbose_name_plural': '库存变动日志'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': '车辆', 'verbose_name_plural': '车辆'},
        ),
        migrations.AlterModelOptions(
            name='worktask',
            options={'verbose_name': '工作任务', 'verbose_name_plural': '工作任务'},
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='distributed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发放时间'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='month',
            field=models.CharField(max_length=20, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='status',
            field=models.CharField(choices=[('pending', '待发放'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='bonusbatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.bonusbatch', verbose_name='批次'),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='领取人'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('driver', '司机'), ('repairman', '修理工'), ('team_leader', '班长'), ('dispatcher', '调度员'), ('admin', '管理员')], default='driver', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班组'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='系统用户'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('on_duty', '在岗'), ('off_duty', '休息')], default='off_duty', max_length=20, verbose_name='出勤状态'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='故障描述'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_repairs', to='fleet.employee', verbose_name='报修人'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='fault_type',
            field=models.CharField(max_length=50, verbose_name='故障类型'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='repairs/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='repairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repairs', to='fleet.employee', verbose_name='维修人员'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('pending', '待维修'), ('repairing', '维修中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='车辆'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='司机'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='mileage',
            field=models.IntegerField(verbose_name='里程'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='凭证图片'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='record_type',
            field=models.CharField(choices=[('fuel', '加油'), ('charge', '充电')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='车辆'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.maintenancerecord', verbose_name='维修单'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem', verbose_name='配件'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='change_amount',
            field=models.IntegerField(verbose_name='变动数量'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.inventoryitem', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.employee', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand_model',
            field=models.CharField(max_length=50, verbose_name='品牌型号'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_vehicle', to='fleet.employee', verbose_name='当前司机'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(default=0, verbose_name='当前里程'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('working', '作业中'), ('repairing', '维修中')], default='idle', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='车辆编号'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assigned_drivers',
            field=models.ManyToManyField(related_name='tasks', to='fleet.employee', verbose_name='指派对象'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='fleet.employee', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='deadline',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='detail',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('doing', '处理中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
