# Generated by Django 5.2.10 on 2026-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_bonusbatch_options_alter_bonusdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='target_team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目标班组'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('driver', '司机'), ('repairman', '点检长'), ('team_leader', '班长'), ('dispatcher', '调度'), ('admin', '管理员')], default='driver', max_length=20, verbose_name='角色'),
        ),
    ]
